### ISSUE TITLE
difference between developit/preact ?

### ISSUE THREAD

**Issue by tommyZZM** [livoras/simple-virtual-dom#6]
https://github.com/developit/preact

**Comment by livoras** [comment]
Actually it's more similar to https://github.com/Matt-Esch/virtual-dom. 

Instead of providing a complete toolkit to help you create view, both `virtual-dom` and `simple-virtual-dom` are just simple modules. Your can integrate it into your own framework/library, for example you want to create another ReactJS but you don't want to write Virtual-DOM yourself.
